export const images: Record<string, any> = {
  '/firstpage.jpg': require('../../assets/firstpage.jpg'),
  '/straight(type1).jpg': require('../../assets/straight(type1).jpg'),
  '/wavy(type2).jpg': require('../../assets/wavy(type2).jpg'),
  '/curly(type3).jpg': require('../../assets/curly(type3).jpg'),
  '/coily(type4).jpg': require('../../assets/coily(type4).jpg'),
  '/BoneStraight.jpg': require('../../assets/BoneStraight.jpg'),
  '/loose-large.jpg': require('../../assets/loose-large.jpg'),
  '/mediumDefined.jpg': require('../../assets/mediumDefined.jpg'),
  '/tightSmall.jpg': require('../../assets/tightSmall.jpg'),
  '/lowPorosity.jpg': require('../../assets/lowPorosity.jpg'),
  '/mediumPorosity.jpg': require('../../assets/mediumPorosity.jpg'),
  '/highPorosity.jpg': require('../../assets/highPorosity.jpg'),
  '/oilyhair.jpg': require('../../assets/oilyhair.jpg'),
  '/balanced.jpg': require('../../assets/balanced.jpg'),
  '/dryhair.jpg': require('../../assets/dryhair.jpg'),
  '/sensitve.jpg': require('../../assets/sensitve.jpg'),
  '/lowdensity.jpg': require('../../assets/lowdensity.jpg'),
  '/mediumdensity.jpg': require('../../assets/mediumdensity.jpg'),
  '/highdensity.jpg': require('../../assets/highdensity.jpg'),
  '/hairgrowth.jpg': require('../../assets/hairgrowth.jpg'),
  '/moisturehydration.jpg': require('../../assets/moisturehydration.jpg'),
  '/curldefinition.jpg': require('../../assets/curldefinition.jpg'),
  '/damagedrepair.jpg': require('../../assets/damagedrepair.jpg'),
  '/volumefulllness.jpg': require('../../assets/volumefulllness.jpg'),
}
